import Head from 'next/head';
import Footer from './Footer';
import Header from './Header';

const Layout = ({ title, children }) => {
  return (
    <div className="bg-primaryDark text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 m-0 p-0">
      <Head>
        <title>
          {title
            ? title + ' - Essex County District Masons}'
            : 'Essex County District Masons'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};
export default Layout;
